In [1]:
import numpy as np

In [7]:
# input layer
inputs = [1, 2, 3, 2.5]
# weights
weights1 = [0.2, 0.8, -0.5, 1.0]
weights2 = [0.5, -0.91, 0.26, -0.5]
weights3 = [-0.26, -0.27, 0.17, 0.87]
bias1 = 2
bias2 = 3
bias3 = 0.5

In [12]:
def compute_single_neuron(inputs, weights, bias):
    output = 0 
    for i in range(len(inputs)):
        output += inputs[i]*weights[i]
    output = output + bias
    return output

In [13]:
# each neuron has its unique set of weights for each input as well as unique bias
weights = [weights1, weights2, weights3]
biases = [bias1, bias2, bias3]
result = []
for weight, bias in zip(weights, biases):
    output = []
    sn_output = compute_single_neuron(inputs, weight, bias)
    result.append(sn_output)
result

[4.8, 1.21, 2.385]

In [16]:
import numpy as np

inputs = [1, 2, 3, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2

output = np.dot(inputs, weights) + bias; output

4.8

In [17]:
weights = [weights1, weights2, weights3]
biases = [bias1, bias2, bias3]

In [18]:
output = np.dot(weights, inputs) + biases; output

array([4.8  , 1.21 , 2.385])

In [26]:
# try batch
inputs = [[1, 2, 3, 2.5], [2.0, 5.0, -1.0, 2.0], [-1.5, 2.7, 3.3, -0.8]]
output = np.dot(inputs, np.array(weights).T) + biases
output


array([[ 4.8  ,  1.21 ,  2.385],
       [ 8.9  , -1.81 ,  0.2  ],
       [ 1.41 ,  1.051,  0.026]])

In [24]:
# create second layer with 3 neurons
weights2 = [[0.1, -0.14, 0.5], [-0.5, 0.12, -0.33], [-0.44, 0.73, 0.13]] 
biases2 = [-1, 2, 0.5]

In [27]:
layer1_output = np.dot(inputs, np.array(weights).T) + biases
layer2_output = np.dot(layer1_output, np.array(weights2).T) + biases2
layer2_output

array([[ 0.5031 , -1.04185, -0.41865],
       [ 0.2434 , -2.7332 , -4.7113 ],
       [-0.99314,  1.41254,  0.65021]])

In [41]:
import numpy as np
# class Neuron Network
X = [[1, 2, 3, 2.5], [2.0, 5.0, -1.0, 2.0], [-1.5, 2.7, 3.3, -0.8]]
class LayerDense:
    np.random.seed(0)
    # init the class with weight and biases 
    def __init__(self, n_inputs, n_neurons):
        # keep weights smaller
        self.weights = 0.10*np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases


In [42]:
# create NN layer with 4 features and 10 neurons 
layer1 = LayerDense(4, 10)
layer2 = LayerDense(10, 2)

layer1.forward(X)
layer2.forward(layer1.output)
print(layer2.output)

[[-0.15836989  0.03885613]
 [-0.34104313 -0.0578446 ]
 [-0.04207106  0.16528394]]


In [ ]:
# Activation functions 
# step function